### ISSUE TITLE
SQLファイルについて

### ISSUE THREAD

**Issue by qeita** [aiaicoco1010/08_38_NakanoAiko_kadai#1]
@aiaicoco1010  
お疲れ様です。G'sチューターのヤギです。  
課題のご提出ありがとうございます。  
  
見た所、SQLファイルがアップされていないようです。  
先日コスゲさんからレクチャーあったように、  
phpmyadminより作ったDBのテーブルをエクスポートしてこちらもgithubにアップいただければと思います。

**Comment by aiaicoco1010** [comment]
ヤギ様

お世話になります。
ご連絡ありがとうございます。
すっかり失念しておりました。
PCが家にありますので、今夜帰って今夜中に対応します。
よろしくお願い申し上げます。


中野愛子

2018年2月2日(金) 17:02 qeita <notifications@github.com>:

**Comment by qeita** [comment]
@aiaicoco1010  
  
ありがとうございます。sqlファイルあげていただけましたので、こちらのissueクローズ致しますね。  
なお、ダウンロードしたphpファイルがこちらで開けないようです。。  
  
https://github.com/aiaicoco1010/08_38_NakanoAiko_kadai/blob/master/index_user.php  
  
上記のように単一ファイルをみると表示されず、    
  
https://github.com/czproject/git-php/blob/master/tests/GitPhp/bootstrap.php  
 
他の人のgitにあげてるphpでは正常に表示されています。  
エンコードがうまくいっていないのかも知れませんので、こちら確認していただけますと幸いです。    
こちら別issueで立てますね。

**Comment by aiaicoco1010** [comment]
ヤギ様

お世話になりありがとうございます。

いわれた通りにやってるつもりなので、要因がわかりません、、
要因もどのあたりにあるのかわからないのですが、どのあたりの何を見直せばいいものでしょうか？

今日早めにいくか残ってここを誰かに教えてもらおうと思いますが、もしヒントあればご一報いただけますと幸いです。

よろしくお願い申し上げます。


中野愛子


2018年2月3日(土) 9:34 qeita <notifications@github.com>:

**Comment by aiaicoco1010** [comment]
やぎ様

お世話になりありがとうございます。
本日学校にきて、問題は解決できました。
ありがとうございました！

中野愛子

2018年2月3日 10:03 中野愛子 <aiaicoco1010@gmail.com>:
